#pragma once
#include "Base.h"

enum EHeroAbility
{
    HERO_ABILITY_NULL,
    HERO_ABILITY_FORCE_PUSH,
    HERO_ABILITY_TIME_SPELL,
    HERO_ABILITY_ENFLAME_SPELL,
    HERO_ABILITY_PHYSICAL_SHIELD_SPELL,
    HERO_ABILITY_TURNCOAT_SPELL,
    HERO_ABILITY_DRAIN_LIFE_SPELL,
    HERO_ABILITY_RAISE_DEAD_SPELL,
    HERO_ABILITY_BERSERK,
    HERO_ABILITY_DOUBLE_STRIKE,
    HERO_ABILITY_SUMMON_SPELL,
    HERO_ABILITY_LIGHTNING_SPELL,
    HERO_ABILITY_BATTLE_CHARGE,
    HERO_ABILITY_ASSASSIN_RUSH,
    HERO_ABILITY_HEAL_LIFE_SPELL,
    HERO_ABILITY_GHOST_SWORD_SPELL,
    HERO_ABILITY_FIREBALL_SPELL,
    HERO_ABILITY_MULTI_ARROW,
    HERO_ABILITY_DIVINE_WRATH_SPELL,
    HERO_ABILITY_UNHOLY_POWER_SPELL,
    MAX_NUMBER_OF_HERO_ABILITIES
};

enum eExperience {
    EXPERIENCE_STRENGTH,
    EXPERIENCE_SKILL,
    EXPERIENCE_WILL,
    TOTAL_EXPERIENCE
};

enum EHeroTitle
{
    TITLE_NONE,
    TITLE_REAPER,
    TITLE_SHADOWHUNTER,
    TITLE_MALEFICUS,
    TITLE_DEATHBRINGER,
    TITLE_ASSASSIN,
    TITLE_NECROMANCER,
    TITLE_AVATAR,
    TITLE_PILGRIM,
    TITLE_LIBERATOR,
    TITLE_PALADIN,
    TITLE_DRUID,
    TITLE_RANGER,
    TITLE_RUNEMASTER,
    TITLE_HOOD,
    TITLE_GLADIATOR,
    TITLE_SABRE,
    TITLE_ARROWDODGER,
    TITLE_PIEMASTER,
    TITLE_CHICKEN_CHASER,
    TITLE_ARSEFACE,
    TITLE_JACK,
    TITLE_MAZE,
    TITLE_SCARLET_ROBE,
    TITLE_SCYTHE,
    TITLE_THUNDER,
    TITLE_WHISPER,
    TITLE_TWINBLADE,
    TITLE_BRIAR_ROSE,
    TITLE_LADY_GREY,
    TITLE_GUILDMASTER,
    TITLE_SCORPION_SLAYER,
    TITLE_DEATH_BRINGER
};

class CTCHero : public CTCBase
{
public:
    bool m_bCanUseWeapons;
    bool m_bCanUseWill;
    bool m_bWeaponsUsable;
    EHeroTitle m_eTitle;

    void SetTitle(int title_def_index);
};

class CTCHeroExperience : public CTCBase {
public:
    char pad[8];
    int  m_nGeneralExperience;
    int* m_pExperience;
};