#pragma once

enum EHeroAbility
{
    HERO_ABILITY_NULL,
    HERO_ABILITY_FORCE_PUSH,
    HERO_ABILITY_TIME_SPELL,
    HERO_ABILITY_ENFLAME_SPELL,
    HERO_ABILITY_PHYSICAL_SHIELD_SPELL,
    HERO_ABILITY_TURNCOAT_SPELL,
    HERO_ABILITY_DRAIN_LIFE_SPELL,
    HERO_ABILITY_RAISE_DEAD_SPELL,
    HERO_ABILITY_BERSERK,
    HERO_ABILITY_DOUBLE_STRIKE,
    HERO_ABILITY_SUMMON_SPELL,
    HERO_ABILITY_LIGHTNING_SPELL,
    HERO_ABILITY_BATTLE_CHARGE,
    HERO_ABILITY_ASSASSIN_RUSH,
    HERO_ABILITY_HEAL_LIFE_SPELL,
    HERO_ABILITY_GHOST_SWORD_SPELL,
    HERO_ABILITY_FIREBALL_SPELL,
    HERO_ABILITY_MULTI_ARROW,
    HERO_ABILITY_DIVINE_WRATH_SPELL,
    HERO_ABILITY_UNHOLY_POWER_SPELL,
    MAX_NUMBER_OF_HERO_ABILITIES
};

class CTCInventoryAbilities
{
public:
	void UpgradeAbility(EHeroAbility ability);
	void ForceAllAbilitesToMaxLevel();
	int GetAbilityLevel(EHeroAbility ability);
};